### ISSUE TITLE
JAVA服务器环境搭建

### ISSUE THREAD

**Issue by onenewnet** [ilanyu/notepad#1]
老大，我对java完全不了解，搭建服务器环境比较头晕，请问一下我用这个配置搭建环境可以吗？需要增减什么吗？

jdk
MySQL
Tomcat
Nginx

感谢！

**Comment by ilanyu** [comment]
可以使用这些

**Comment by onenewnet** [comment]
多谢解答！

**Comment by onenewnet** [comment]
环境是搭好了，不会架设……研究了几天失败告终，哎
